### PR TITLE
Add TDD by Example by Kent Beck

### PR DESCRIPTION
**Pull request by rradczewski**

### CODE REVIEW

**Review by jukecraft — APPROVED** [review]
good addition!

**Comment by rradczewski** [comment]
Thanks @tdpauw! I changed two tiny things in 7cd124a - if that's alright with you I'd merge it right away :+1:

**Comment by tdpauw** [comment]
Thanks @franziskas and @rradczewski !
I'm ok with the changes. I could have mentioned that following the steps with an editor helps in getting a better understanding. Don't know if that is relevant.

**Comment by rradczewski** [comment]
> I could have mentioned that following the steps with an editor helps in getting a better understanding.

I think that's an assumption we can take for granted :+1: Thanks for your review!

**Pull request merged**
