### PR TITLE
Add The Phoenix Project & The Goal

### PR DESCRIPTION
**Pull request by rradczewski**

### CODE REVIEW

**Comment by tdpauw** [comment]
This is still a work in progress.

**Comment by tdpauw** [comment]
This PR is ready for review.

**Comment by rradczewski** [comment]
Thanks for adding the other books, I haven't heard about *Rolling Rocks Downhill* before, gonna look into it!

**Comment by tdpauw** [comment]
Me neither, until Clarke was keynote speaker at Lean Agile Scotland and someone told me: Well, you know he wrote Rolling Rocks Downhill, a novel like The Goal. And then I found out he was going to release The Bottleneck Rules.

**Comment by rradczewski** [comment]
Into my reading backlog it goes :sweat_smile:

**Pull request merged**
